let ism = prompt("Ismingizni kiriting");
console.log(ism);
let familiya = prompt("Familiyangizni kiriting");
console.log(familiya);
let yosh = prompt("Yoshingizni kiriting");
console.log(yosh);
let fan = prompt("Yoqtirgan faningizni yozing");
console.log(fan);
let tuman = prompt("Yashaydigan tumaningizni kiriting");
alert("malumotlaringizni kiritganingiz uchun raxmat");
console.log(tuman);